### ISSUE TITLE
A11y Support

### ISSUE THREAD

**Issue by pointhalo** [DouyinFE/semi-design#205]
### Which Component Need Enhancement 期望新增功能的组件
Add a11y support for All Semi components

### Feature Description 功能描述
[] WAI-ARIA
[] More components support keyboard operation
[] (To be added)

**Comment by shijiatongxue** [comment]
# A11y To do

## Modal
- [ ] Add esc key listener
- [ ] Focus dropdown when visible
- [ ] button onKeydown listen 'Enter' key

**Comment by shijiatongxue** [comment]
## label locale adapter

内置 label 需要根据 locale 进行适配。

The built-in label needs to be adapted according to the locale.

**Comment by pointhalo** [comment]
Update the latest progress
-----
更新同步一下最近的进度

### 已完成
在v2.3版本，我们完成了将近 40+ 组件的 WAI-ARIA 支持，且对于已完成改造的组件，我们在其文档底部增加了详细的Accessibility说明。
详情可以查看我们的changelog
![image](https://user-images.githubusercontent.com/88709023/154022942-45d7742d-2a91-4e30-acec-ee41fd714fb1.png)
![image](https://user-images.githubusercontent.com/88709023/154023104-3f384cea-95bf-4271-8b71-1af648346735.png)

### TODO
关于 a11y的 剩余todo事项包括
- 剩余10+组件的  WAI-ARIA 支持
- 按照规范将需要支持键盘事件的组件进行改造

目前我们已经完成所有键盘事项todo的梳理，在 v2.5 版本开始，我们会陆续将键盘事件按照标准进行支持实现

**预计在2-3个minor版本后， Semi 的无障碍支持将达到一个相对完整的地步**

-----

In the v2.3 version, we have completed the WAI-ARIA support for nearly 40+ components and for the components that have been retrofitted, we have added detailed Accessibility instructions at the bottom of their documents. For details, please check our changelog
![image](https://user-images.githubusercontent.com/88709023/154023682-45a14834-47fa-43d6-9536-ff35854b09b9.png)

![image](https://user-images.githubusercontent.com/88709023/154023612-1bf2c7c1-6921-475a-b4ab-59f7e252ad12.png)

Remaining todos about a11y include
- WAI-ARIA support for the remaining 10+ components
- Modify components that need to support keyboard events according to the specification

At present, we have completed the sorting of all keyboard events todo. It is expected that starting from the v2.5 version, we will gradually support and implement keyboard events according to the standard.

It is expected that after 2-3 minor versions, Semi's accessibility support will reach a relatively complete level

**Comment by pointhalo** [comment]
In addition, in addition to the necessary A11y modifications for the Semi components themselves, we also plan to provide corresponding accessibility support for the Semi documentation site.

Our goal
- Site focus accessibility
- Site semantic accessibility
- Site demo accessibility

Accessible areas include
- Site header
- Site banner
- Main site content
   - Component Navigation
   - Content sidebar
   - Body title
   - Toggle Tab between API documentation and design documentation
   - code demo area
   - All jump links

Accessibility support for the site will start after the component's A11y support has reached a relatively complete state
